modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = ""
license = "LGPL-3.0-only"

[[mods]]
modId = "soul_ice"
version = "${version}"
displayName = "Soul Ice"
displayURL = ""
authors = [
    "Siuol"
]
description = '''
Soul Ice (Flushed Emoji)
'''
logoFile = "icon.png"

[[dependencies.soul_ice]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soul_ice]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"
